# Generated by Django 4.0.4 on 2022-04-30 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag1',
        ),
        migrations.AddField(
            model_name='post',
            name='tag2',
            field=models.CharField(default=datetime.datetime(2022, 4, 30, 17, 28, 44, 737611, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.CharField(max_length=1000),
        ),
    ]
