# Generated by Django 4.0.4 on 2022-04-30 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0002_rename_tags_post_tag1_post_tag2_alter_post_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.AddField(
            model_name='post',
            name='dou',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
