# Generated by Django 4.0.4 on 2022-04-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmapp', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
